import type { Metadata } from "next";

import "@/app/index.css";
import ClientLayoutWrapper from "./_ui/ClientLayoutWrapper";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="dark">
      <ClientLayoutWrapper>
        {children}
        <div id="portal-root"></div>
      </ClientLayoutWrapper>
    </html>
  );
}
